export const icons = [
    "snowflake-o",
    "eercast",
    "ravelry",
    "car",
    "briefcase",
    "cogs",
    "cubes",
    "flask",
    "graduation-cap",
    "university",
    "paper-plane-o",
    "retweet",
    "server",
];
